[package]
authors = ["devj <power3xz@gmail.com>"]
edition = "2021"
name = "bp"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
chrono-tz = "0.6.1"
